### ISSUE TITLE
[Carousel] User-select

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/carousel#2]
_From @jimdebeer on March 7, 2016 16:20_

on the webversion lets disable user select on the carousel, when you try to drag you copy the image its a little bit strange

_Copied from original issue: vigour-io/play#131_

**Comment by nikoloza** [comment]
Fixed in here: https://github.com/vigour-io/play/commit/5cc270cd0b299257497ec30c2483c6485e16deeb
